[project]
name = "hkust-ip-dp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.2",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pulp>=3.1.1",
    "tqdm>=4.67.1",
]
